import Image from "next/legacy/image";

function page() {
    return ( 
        <main className="content mt-10">
            <h1 className="text-2xl text-center mb-3 text-black font-semibold">Tutorial CRUD (create, read, update and delete) with framework laravel.</h1>
            <p className="mb-10 text-gray-600 text-center">20 Juni 2023 - <span className="font-semibold text-black">Heri Setyawan</span></p>
            <div className="relative mx-auto bg-blue-500 w-3/4 h-[425px]">
                <Image layout="fill" src="https://images.unsplash.com/photo-1532289735437-a07b8f3240e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8bmV4dCUyMGpzfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60" className="absolute" loading="lazy" alt="img-blog" />
            </div>
            <div className="mt-20 w-full px-10 space-y-5">
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, illo laboriosam obcaecati quo error asperiores? Iure error sed sapiente. Modi molestias accusantium et, quas repudiandae in, suscipit molestiae quidem atque reiciendis maxime iure autem, expedita optio eligendi! Esse saepe iste porro, veritatis deserunt cumque id atque natus. Cumque aspernatur aliquam veritatis facilis consectetur recusandae, porro architecto, ea voluptatibus assumenda ullam et velit quas quae voluptatum ex sapiente! Beatae mollitia nisi ipsam. Tenetur in eos suscipit nam alias earum impedit aliquid ab quisquam odio quis nihil repellendus debitis id ipsum dolores totam, voluptatum dignissimos dolore itaque quia aperiam harum. Exercitationem quidem nemo nobis odit autem dolorum quo tempore! Labore magni ratione doloremque earum qui pariatur molestiae mollitia ipsam modi minus ducimus enim iusto, sequi sapiente odit alias non obcaecati, libero maiores tempora in iure. Cupiditate corrupti assumenda voluptate incidunt exercitationem ducimus laborum rem beatae aliquid perspiciatis alias dolor deleniti, quisquam rerum! Quaerat veritatis provident tenetur architecto. Hic facilis doloribus distinctio reprehenderit magni eius nihil cupiditate ad, itaque aperiam harum totam provident error consectetur, at in recusandae molestias alias labore beatae! Et, repellendus? Odit natus provident saepe maxime animi dolores illo. Excepturi, ex itaque. Voluptates explicabo recusandae maiores inventore enim dolor iste.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, illo laboriosam obcaecati quo error asperiores? Iure error sed sapiente. Modi molestias accusantium et, quas repudiandae in, suscipit molestiae quidem atque reiciendis maxime iure autem, expedita optio eligendi! Esse saepe iste porro, veritatis deserunt cumque id atque natus. Cumque aspernatur aliquam veritatis facilis consectetur recusandae, porro architecto, ea voluptatibus assumenda ullam et velit quas quae voluptatum ex sapiente! Beatae mollitia nisi ipsam. Tenetur in eos suscipit nam alias earum impedit aliquid ab quisquam odio quis nihil repellendus debitis id ipsum dolores totam, voluptatum dignissimos dolore itaque quia aperiam harum. Exercitationem quidem nemo nobis odit autem dolorum quo tempore! Labore magni ratione doloremque earum qui pariatur molestiae mollitia ipsam modi minus ducimus enim iusto, sequi sapiente odit alias non obcaecati, libero maiores tempora in iure. Cupiditate corrupti assumenda voluptate incidunt exercitationem ducimus laborum rem beatae aliquid perspiciatis alias dolor deleniti, quisquam rerum! Quaerat veritatis provident tenetur architecto. Hic facilis doloribus distinctio reprehenderit magni eius nihil cupiditate ad, itaque aperiam harum totam provident error consectetur, at in recusandae molestias alias labore beatae! Et, repellendus? Odit natus provident saepe maxime animi dolores illo. Excepturi, ex itaque. Voluptates explicabo recusandae maiores inventore enim dolor iste.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, illo laboriosam obcaecati quo error asperiores? Iure error sed sapiente. Modi molestias accusantium et, quas repudiandae in, suscipit molestiae quidem atque reiciendis maxime iure autem, expedita optio eligendi! Esse saepe iste porro, veritatis deserunt cumque id atque natus. Cumque aspernatur aliquam veritatis facilis consectetur recusandae, porro architecto, ea voluptatibus assumenda ullam et velit quas quae voluptatum ex sapiente! Beatae mollitia nisi ipsam. Tenetur in eos suscipit nam alias earum impedit aliquid ab quisquam odio quis nihil repellendus debitis id ipsum dolores totam, voluptatum dignissimos dolore itaque quia aperiam harum. Exercitationem quidem nemo nobis odit autem dolorum quo tempore! Labore magni ratione doloremque earum qui pariatur molestiae mollitia ipsam modi minus ducimus enim iusto, sequi sapiente odit alias non obcaecati, libero maiores tempora in iure. Cupiditate corrupti assumenda voluptate incidunt exercitationem ducimus laborum rem beatae aliquid perspiciatis alias dolor deleniti, quisquam rerum! Quaerat veritatis provident tenetur architecto. Hic facilis doloribus distinctio reprehenderit magni eius nihil cupiditate ad, itaque aperiam harum totam provident error consectetur, at in recusandae molestias alias labore beatae! Et, repellendus? Odit natus provident saepe maxime animi dolores illo. Excepturi, ex itaque. Voluptates explicabo recusandae maiores inventore enim dolor iste.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, illo laboriosam obcaecati quo error asperiores? Iure error sed sapiente. Modi molestias accusantium et, quas repudiandae in, suscipit molestiae quidem atque reiciendis maxime iure autem, expedita optio eligendi! Esse saepe iste porro, veritatis deserunt cumque id atque natus. Cumque aspernatur aliquam veritatis facilis consectetur recusandae, porro architecto, ea voluptatibus assumenda ullam et velit quas quae voluptatum ex sapiente! Beatae mollitia nisi ipsam. Tenetur in eos suscipit nam alias earum impedit aliquid ab quisquam odio quis nihil repellendus debitis id ipsum dolores totam, voluptatum dignissimos dolore itaque quia aperiam harum. Exercitationem quidem nemo nobis odit autem dolorum quo tempore! Labore magni ratione doloremque earum qui pariatur molestiae mollitia ipsam modi minus ducimus enim iusto, sequi sapiente odit alias non obcaecati, libero maiores tempora in iure. Cupiditate corrupti assumenda voluptate incidunt exercitationem ducimus laborum rem beatae aliquid perspiciatis alias dolor deleniti, quisquam rerum! Quaerat veritatis provident tenetur architecto. Hic facilis doloribus distinctio reprehenderit magni eius nihil cupiditate ad, itaque aperiam harum totam provident error consectetur, at in recusandae molestias alias labore beatae! Et, repellendus? Odit natus provident saepe maxime animi dolores illo. Excepturi, ex itaque. Voluptates explicabo recusandae maiores inventore enim dolor iste.</p>
            </div>
        </main>
     );
}

export default page;