import Navbar from './(components)/navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Artikel pribadi yang di publish',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar menuList={[]} />
        {children}
        <footer className='bg-black text-white content'>
          <h1 className='text-2xl font-semibold'>
            Blog Technology
          </h1>
        </footer>
      </body>
    </html>
  )
}
